#!/bin/bash
start() {
	/usr/bin/python startup_email.py generic.conf
}
# Restart the service FOO
stop() {
	echo "stop"
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
